[tool.poetry]
name = "NightWatch"
version = "0.0.0" # Version is ignored and set by Tekton. Use pipeline to increase.
description = "And now my watch begins"
authors = ["Haefelin Julien <jhaefelin-git@aliasdesk.ch>"]
repository = "https://github.com/Julien-hae/NightWatch.git"
documentation = "https://github.com/Julien-hae/NightWatch/blob/master/README.md"
packages = [{include = "Nightwatch", from = "src"}]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
numpy = "~1.26"                                     # NumPy is the fundamental package for array computing with Python.
alpaca-py = "^0.43.2"
pytz = "^2025.2"
python-dotenv = "^1.2.1"
websockets = "^16.0"

[tool.poetry.group.dev.dependencies]
coverage = {extras = ["toml"], version = "~7.4"}    # Code coverage measurement for Python
unittest-xml-reporting = "~3.2"                     # unittest-based test runner with Ant/JUnit like XML reporting.
pre-commit = "~3.6"                                 # A framework for managing and maintaining multi-language pre-commit hooks.
pre-commit-hooks = "~4.5"                           # Some out-of-the-box hooks for pre-commit.
# NOTE: pylint-sonarjson is incompatible with pylint 3.x, hence we can't update yet, see also: https://github.com/omegacen/pylint-sonarjson/pull/12
mypy = "~1.8"                                       # Tool for static type-checking
ruff = "^0.14.14"
ipykernel = "^7.2.0"

[tool.poetry.scripts]
entrypoint = 'Nightwatch.main:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.11"
plugins = "numpy.typing.mypy_plugin"
strict = true

[tool.coverage.run]
command_line = "-m xmlrunner discover --output-file junittest.xml"

[tool.ruff]
line-length = 140
indent-width = 4

exclude = [
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".pyenv",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "**/*.yaml",
    "**/*.yml"
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint]
select = [
    "D", "E", "W",  # Pydocstyle rules
    "I",            # Isort rules
    "PL",           # Pylint rules
    "F",            # Pyflake
    "N",            # Pep8-naming
    "G",            # Flake8-logging-format
    "ARG",          # Flake8-unused-arguments
    ]
ignore=[]
fixable = ["I"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D", "E", "W"] # Ignore Pydocstyle warnings & errors in "test/*" directory

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-args = 8
