"""Module defining the Strategy abstract base class."""

from abc import ABC, abstractmethod
from collections import deque

from Nightwatch.models.market_tick import MarketTick
from Nightwatch.models.signal import Signal


class Strategy(ABC):
    """Abstract base class for trading strategies."""

    @abstractmethod
    def on_tick(self, symbol: str, window: deque[MarketTick]) -> Signal | None:
        """Method to be implemented by concrete strategies to handle market ticks.

        Args:
            symbol (str): The symbol for which the market tick is received.
            window (deque[MarketTick]): A deque containing the recent market ticks.

        Returns:
            Signal | None: The trading signal generated by the strategy, or None if no signal is generated.
        """
